[package]
name = "web-os"
version = "0.1.0"
edition = "2021"
author = ["Lu√≠s Silva <luisfelipeluis49@gmail.com>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
